receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
      http:
        endpoint: 0.0.0.0:4318

processors:
  batch:

exporters:
  azuremonitor:
    connection_string: InstrumentationKey=c96ac62b-b56e-4efa-8637-8dfaa388c49e;IngestionEndpoint=https://japaneast-1.in.applicationinsights.azure.com/;LiveEndpoint=https://japaneast.livediagnostics.monitor.azure.com/;ApplicationId=0fddd1be-1bdc-4838-9ad3-020c7be81eff

pipelines:
  traces:
    receivers: [otlp]
    processors: [batch]
    exporters: [azuremonitor]
  # metrics:
  #   receivers: [otlp]
  #   processors: [batch]
  #   exporters: [azuremonitor]
  # logs:
  #   receivers: [otlp]
  #   processors: [batch]
  #   exporters: [azuremonitor]
