receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
      http:
        endpoint: 0.0.0.0:4318

processors:
  batch:

exporters:
  azuremonitor:
    connection_string: ${env:CONNECTION_STRING}

service:
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [azuremonitor]
    # metrics:
    #   receivers: [otlp]
    #   processors: [batch]
    #   exporters: [azuremonitor]
    # logs:
    #   receivers: [otlp]
    #   processors: [batch]
    #   exporters: [azuremonitor]
